// Generated by the gRPC C++ plugin.
// If you make any local change, they will be lost.
// source: meeting_ai.proto
#ifndef GRPC_meeting_5fai_2eproto__INCLUDED
#define GRPC_meeting_5fai_2eproto__INCLUDED

#include "meeting_ai.pb.h"

#include <functional>
#include <grpcpp/generic/async_generic_service.h>
#include <grpcpp/support/async_stream.h>
#include <grpcpp/support/async_unary_call.h>
#include <grpcpp/support/client_callback.h>
#include <grpcpp/client_context.h>
#include <grpcpp/completion_queue.h>
#include <grpcpp/support/message_allocator.h>
#include <grpcpp/support/method_handler.h>
#include <grpcpp/impl/codegen/proto_utils.h>
#include <grpcpp/impl/rpc_method.h>
#include <grpcpp/support/server_callback.h>
#include <grpcpp/impl/codegen/server_callback_handlers.h>
#include <grpcpp/server_context.h>
#include <grpcpp/impl/service_type.h>
#include <grpcpp/impl/codegen/status.h>
#include <grpcpp/support/stub_options.h>
#include <grpcpp/support/sync_stream.h>

namespace message {

// 会议内普通文本问答接口。
// 该能力不绑定 meeting_id，不读取音频，也不携带会议历史上下文。
class MeetingAiService final {
 public:
  static constexpr char const* service_full_name() {
    return "message.MeetingAiService";
  }
  class StubInterface {
   public:
    virtual ~StubInterface() {}
    virtual ::grpc::Status AskAssistant(::grpc::ClientContext* context, const ::message::AskAssistantRequest& request, ::message::AskAssistantResponse* response) = 0;
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::message::AskAssistantResponse>> AsyncAskAssistant(::grpc::ClientContext* context, const ::message::AskAssistantRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::message::AskAssistantResponse>>(AsyncAskAssistantRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::message::AskAssistantResponse>> PrepareAsyncAskAssistant(::grpc::ClientContext* context, const ::message::AskAssistantRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::message::AskAssistantResponse>>(PrepareAsyncAskAssistantRaw(context, request, cq));
    }
    class async_interface {
     public:
      virtual ~async_interface() {}
      virtual void AskAssistant(::grpc::ClientContext* context, const ::message::AskAssistantRequest* request, ::message::AskAssistantResponse* response, std::function<void(::grpc::Status)>) = 0;
      virtual void AskAssistant(::grpc::ClientContext* context, const ::message::AskAssistantRequest* request, ::message::AskAssistantResponse* response, ::grpc::ClientUnaryReactor* reactor) = 0;
    };
    typedef class async_interface experimental_async_interface;
    virtual class async_interface* async() { return nullptr; }
    class async_interface* experimental_async() { return async(); }
   private:
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::message::AskAssistantResponse>* AsyncAskAssistantRaw(::grpc::ClientContext* context, const ::message::AskAssistantRequest& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::message::AskAssistantResponse>* PrepareAsyncAskAssistantRaw(::grpc::ClientContext* context, const ::message::AskAssistantRequest& request, ::grpc::CompletionQueue* cq) = 0;
  };
  class Stub final : public StubInterface {
   public:
    Stub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options = ::grpc::StubOptions());
    ::grpc::Status AskAssistant(::grpc::ClientContext* context, const ::message::AskAssistantRequest& request, ::message::AskAssistantResponse* response) override;
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::message::AskAssistantResponse>> AsyncAskAssistant(::grpc::ClientContext* context, const ::message::AskAssistantRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::message::AskAssistantResponse>>(AsyncAskAssistantRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::message::AskAssistantResponse>> PrepareAsyncAskAssistant(::grpc::ClientContext* context, const ::message::AskAssistantRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::message::AskAssistantResponse>>(PrepareAsyncAskAssistantRaw(context, request, cq));
    }
    class async final :
      public StubInterface::async_interface {
     public:
      void AskAssistant(::grpc::ClientContext* context, const ::message::AskAssistantRequest* request, ::message::AskAssistantResponse* response, std::function<void(::grpc::Status)>) override;
      void AskAssistant(::grpc::ClientContext* context, const ::message::AskAssistantRequest* request, ::message::AskAssistantResponse* response, ::grpc::ClientUnaryReactor* reactor) override;
     private:
      friend class Stub;
      explicit async(Stub* stub): stub_(stub) { }
      Stub* stub() { return stub_; }
      Stub* stub_;
    };
    class async* async() override { return &async_stub_; }

   private:
    std::shared_ptr< ::grpc::ChannelInterface> channel_;
    class async async_stub_{this};
    ::grpc::ClientAsyncResponseReader< ::message::AskAssistantResponse>* AsyncAskAssistantRaw(::grpc::ClientContext* context, const ::message::AskAssistantRequest& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientAsyncResponseReader< ::message::AskAssistantResponse>* PrepareAsyncAskAssistantRaw(::grpc::ClientContext* context, const ::message::AskAssistantRequest& request, ::grpc::CompletionQueue* cq) override;
    const ::grpc::internal::RpcMethod rpcmethod_AskAssistant_;
  };
  static std::unique_ptr<Stub> NewStub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options = ::grpc::StubOptions());

  class Service : public ::grpc::Service {
   public:
    Service();
    virtual ~Service();
    virtual ::grpc::Status AskAssistant(::grpc::ServerContext* context, const ::message::AskAssistantRequest* request, ::message::AskAssistantResponse* response);
  };
  template <class BaseClass>
  class WithAsyncMethod_AskAssistant : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithAsyncMethod_AskAssistant() {
      ::grpc::Service::MarkMethodAsync(0);
    }
    ~WithAsyncMethod_AskAssistant() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status AskAssistant(::grpc::ServerContext* /*context*/, const ::message::AskAssistantRequest* /*request*/, ::message::AskAssistantResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestAskAssistant(::grpc::ServerContext* context, ::message::AskAssistantRequest* request, ::grpc::ServerAsyncResponseWriter< ::message::AskAssistantResponse>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(0, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  typedef WithAsyncMethod_AskAssistant<Service > AsyncService;
  template <class BaseClass>
  class WithCallbackMethod_AskAssistant : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithCallbackMethod_AskAssistant() {
      ::grpc::Service::MarkMethodCallback(0,
          new ::grpc::internal::CallbackUnaryHandler< ::message::AskAssistantRequest, ::message::AskAssistantResponse>(
            [this](
                   ::grpc::CallbackServerContext* context, const ::message::AskAssistantRequest* request, ::message::AskAssistantResponse* response) { return this->AskAssistant(context, request, response); }));}
    void SetMessageAllocatorFor_AskAssistant(
        ::grpc::MessageAllocator< ::message::AskAssistantRequest, ::message::AskAssistantResponse>* allocator) {
      ::grpc::internal::MethodHandler* const handler = ::grpc::Service::GetHandler(0);
      static_cast<::grpc::internal::CallbackUnaryHandler< ::message::AskAssistantRequest, ::message::AskAssistantResponse>*>(handler)
              ->SetMessageAllocator(allocator);
    }
    ~WithCallbackMethod_AskAssistant() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status AskAssistant(::grpc::ServerContext* /*context*/, const ::message::AskAssistantRequest* /*request*/, ::message::AskAssistantResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerUnaryReactor* AskAssistant(
      ::grpc::CallbackServerContext* /*context*/, const ::message::AskAssistantRequest* /*request*/, ::message::AskAssistantResponse* /*response*/)  { return nullptr; }
  };
  typedef WithCallbackMethod_AskAssistant<Service > CallbackService;
  typedef CallbackService ExperimentalCallbackService;
  template <class BaseClass>
  class WithGenericMethod_AskAssistant : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithGenericMethod_AskAssistant() {
      ::grpc::Service::MarkMethodGeneric(0);
    }
    ~WithGenericMethod_AskAssistant() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status AskAssistant(::grpc::ServerContext* /*context*/, const ::message::AskAssistantRequest* /*request*/, ::message::AskAssistantResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
  };
  template <class BaseClass>
  class WithRawMethod_AskAssistant : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawMethod_AskAssistant() {
      ::grpc::Service::MarkMethodRaw(0);
    }
    ~WithRawMethod_AskAssistant() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status AskAssistant(::grpc::ServerContext* /*context*/, const ::message::AskAssistantRequest* /*request*/, ::message::AskAssistantResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestAskAssistant(::grpc::ServerContext* context, ::grpc::ByteBuffer* request, ::grpc::ServerAsyncResponseWriter< ::grpc::ByteBuffer>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(0, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithRawCallbackMethod_AskAssistant : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawCallbackMethod_AskAssistant() {
      ::grpc::Service::MarkMethodRawCallback(0,
          new ::grpc::internal::CallbackUnaryHandler< ::grpc::ByteBuffer, ::grpc::ByteBuffer>(
            [this](
                   ::grpc::CallbackServerContext* context, const ::grpc::ByteBuffer* request, ::grpc::ByteBuffer* response) { return this->AskAssistant(context, request, response); }));
    }
    ~WithRawCallbackMethod_AskAssistant() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status AskAssistant(::grpc::ServerContext* /*context*/, const ::message::AskAssistantRequest* /*request*/, ::message::AskAssistantResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerUnaryReactor* AskAssistant(
      ::grpc::CallbackServerContext* /*context*/, const ::grpc::ByteBuffer* /*request*/, ::grpc::ByteBuffer* /*response*/)  { return nullptr; }
  };
  template <class BaseClass>
  class WithStreamedUnaryMethod_AskAssistant : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithStreamedUnaryMethod_AskAssistant() {
      ::grpc::Service::MarkMethodStreamed(0,
        new ::grpc::internal::StreamedUnaryHandler<
          ::message::AskAssistantRequest, ::message::AskAssistantResponse>(
            [this](::grpc::ServerContext* context,
                   ::grpc::ServerUnaryStreamer<
                     ::message::AskAssistantRequest, ::message::AskAssistantResponse>* streamer) {
                       return this->StreamedAskAssistant(context,
                         streamer);
                  }));
    }
    ~WithStreamedUnaryMethod_AskAssistant() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable regular version of this method
    ::grpc::Status AskAssistant(::grpc::ServerContext* /*context*/, const ::message::AskAssistantRequest* /*request*/, ::message::AskAssistantResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    // replace default version of method with streamed unary
    virtual ::grpc::Status StreamedAskAssistant(::grpc::ServerContext* context, ::grpc::ServerUnaryStreamer< ::message::AskAssistantRequest,::message::AskAssistantResponse>* server_unary_streamer) = 0;
  };
  typedef WithStreamedUnaryMethod_AskAssistant<Service > StreamedUnaryService;
  typedef Service SplitStreamedService;
  typedef WithStreamedUnaryMethod_AskAssistant<Service > StreamedService;
};

}  // namespace message


#endif  // GRPC_meeting_5fai_2eproto__INCLUDED
