// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: meeting_ai.proto

#ifndef GOOGLE_PROTOBUF_INCLUDED_meeting_5fai_2eproto
#define GOOGLE_PROTOBUF_INCLUDED_meeting_5fai_2eproto

#include <limits>
#include <string>

#include <google/protobuf/port_def.inc>
#if PROTOBUF_VERSION < 3021000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers. Please update
#error your headers.
#endif
#if 3021012 < PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers. Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/port_undef.inc>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/metadata_lite.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>  // IWYU pragma: export
#include <google/protobuf/extension_set.h>  // IWYU pragma: export
#include <google/protobuf/unknown_field_set.h>
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>
#define PROTOBUF_INTERNAL_EXPORT_meeting_5fai_2eproto
PROTOBUF_NAMESPACE_OPEN
namespace internal {
class AnyMetadata;
}  // namespace internal
PROTOBUF_NAMESPACE_CLOSE

// Internal implementation detail -- do not use these members.
struct TableStruct_meeting_5fai_2eproto {
  static const uint32_t offsets[];
};
extern const ::PROTOBUF_NAMESPACE_ID::internal::DescriptorTable descriptor_table_meeting_5fai_2eproto;
namespace message {
class AskAssistantRequest;
struct AskAssistantRequestDefaultTypeInternal;
extern AskAssistantRequestDefaultTypeInternal _AskAssistantRequest_default_instance_;
class AskAssistantResponse;
struct AskAssistantResponseDefaultTypeInternal;
extern AskAssistantResponseDefaultTypeInternal _AskAssistantResponse_default_instance_;
}  // namespace message
PROTOBUF_NAMESPACE_OPEN
template<> ::message::AskAssistantRequest* Arena::CreateMaybeMessage<::message::AskAssistantRequest>(Arena*);
template<> ::message::AskAssistantResponse* Arena::CreateMaybeMessage<::message::AskAssistantResponse>(Arena*);
PROTOBUF_NAMESPACE_CLOSE
namespace message {

// ===================================================================

class AskAssistantRequest final :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:message.AskAssistantRequest) */ {
 public:
  inline AskAssistantRequest() : AskAssistantRequest(nullptr) {}
  ~AskAssistantRequest() override;
  explicit PROTOBUF_CONSTEXPR AskAssistantRequest(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  AskAssistantRequest(const AskAssistantRequest& from);
  AskAssistantRequest(AskAssistantRequest&& from) noexcept
    : AskAssistantRequest() {
    *this = ::std::move(from);
  }

  inline AskAssistantRequest& operator=(const AskAssistantRequest& from) {
    CopyFrom(from);
    return *this;
  }
  inline AskAssistantRequest& operator=(AskAssistantRequest&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetOwningArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const AskAssistantRequest& default_instance() {
    return *internal_default_instance();
  }
  static inline const AskAssistantRequest* internal_default_instance() {
    return reinterpret_cast<const AskAssistantRequest*>(
               &_AskAssistantRequest_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    0;

  friend void swap(AskAssistantRequest& a, AskAssistantRequest& b) {
    a.Swap(&b);
  }
  inline void Swap(AskAssistantRequest* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() != nullptr &&
        GetOwningArena() == other->GetOwningArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() == other->GetOwningArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(AskAssistantRequest* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  AskAssistantRequest* New(::PROTOBUF_NAMESPACE_ID::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<AskAssistantRequest>(arena);
  }
  using ::PROTOBUF_NAMESPACE_ID::Message::CopyFrom;
  void CopyFrom(const AskAssistantRequest& from);
  using ::PROTOBUF_NAMESPACE_ID::Message::MergeFrom;
  void MergeFrom( const AskAssistantRequest& from) {
    AskAssistantRequest::MergeImpl(*this, from);
  }
  private:
  static void MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg);
  public:
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  uint8_t* _InternalSerialize(
      uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::PROTOBUF_NAMESPACE_ID::Arena* arena, bool is_message_owned);
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(AskAssistantRequest* other);

  private:
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "message.AskAssistantRequest";
  }
  protected:
  explicit AskAssistantRequest(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                       bool is_message_owned = false);
  public:

  static const ClassData _class_data_;
  const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*GetClassData() const final;

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kQuestionFieldNumber = 1,
  };
  // string question = 1;
  void clear_question();
  const std::string& question() const;
  template <typename ArgT0 = const std::string&, typename... ArgT>
  void set_question(ArgT0&& arg0, ArgT... args);
  std::string* mutable_question();
  PROTOBUF_NODISCARD std::string* release_question();
  void set_allocated_question(std::string* question);
  private:
  const std::string& _internal_question() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_question(const std::string& value);
  std::string* _internal_mutable_question();
  public:

  // @@protoc_insertion_point(class_scope:message.AskAssistantRequest)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  struct Impl_ {
    ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr question_;
    mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_meeting_5fai_2eproto;
};
// -------------------------------------------------------------------

class AskAssistantResponse final :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:message.AskAssistantResponse) */ {
 public:
  inline AskAssistantResponse() : AskAssistantResponse(nullptr) {}
  ~AskAssistantResponse() override;
  explicit PROTOBUF_CONSTEXPR AskAssistantResponse(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  AskAssistantResponse(const AskAssistantResponse& from);
  AskAssistantResponse(AskAssistantResponse&& from) noexcept
    : AskAssistantResponse() {
    *this = ::std::move(from);
  }

  inline AskAssistantResponse& operator=(const AskAssistantResponse& from) {
    CopyFrom(from);
    return *this;
  }
  inline AskAssistantResponse& operator=(AskAssistantResponse&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetOwningArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const AskAssistantResponse& default_instance() {
    return *internal_default_instance();
  }
  static inline const AskAssistantResponse* internal_default_instance() {
    return reinterpret_cast<const AskAssistantResponse*>(
               &_AskAssistantResponse_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    1;

  friend void swap(AskAssistantResponse& a, AskAssistantResponse& b) {
    a.Swap(&b);
  }
  inline void Swap(AskAssistantResponse* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() != nullptr &&
        GetOwningArena() == other->GetOwningArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() == other->GetOwningArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(AskAssistantResponse* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  AskAssistantResponse* New(::PROTOBUF_NAMESPACE_ID::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<AskAssistantResponse>(arena);
  }
  using ::PROTOBUF_NAMESPACE_ID::Message::CopyFrom;
  void CopyFrom(const AskAssistantResponse& from);
  using ::PROTOBUF_NAMESPACE_ID::Message::MergeFrom;
  void MergeFrom( const AskAssistantResponse& from) {
    AskAssistantResponse::MergeImpl(*this, from);
  }
  private:
  static void MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg);
  public:
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  uint8_t* _InternalSerialize(
      uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::PROTOBUF_NAMESPACE_ID::Arena* arena, bool is_message_owned);
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(AskAssistantResponse* other);

  private:
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "message.AskAssistantResponse";
  }
  protected:
  explicit AskAssistantResponse(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                       bool is_message_owned = false);
  public:

  static const ClassData _class_data_;
  const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*GetClassData() const final;

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kAnswerFieldNumber = 2,
    kErrorMessageFieldNumber = 3,
    kErrorFieldNumber = 1,
  };
  // string answer = 2;
  void clear_answer();
  const std::string& answer() const;
  template <typename ArgT0 = const std::string&, typename... ArgT>
  void set_answer(ArgT0&& arg0, ArgT... args);
  std::string* mutable_answer();
  PROTOBUF_NODISCARD std::string* release_answer();
  void set_allocated_answer(std::string* answer);
  private:
  const std::string& _internal_answer() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_answer(const std::string& value);
  std::string* _internal_mutable_answer();
  public:

  // string error_message = 3;
  void clear_error_message();
  const std::string& error_message() const;
  template <typename ArgT0 = const std::string&, typename... ArgT>
  void set_error_message(ArgT0&& arg0, ArgT... args);
  std::string* mutable_error_message();
  PROTOBUF_NODISCARD std::string* release_error_message();
  void set_allocated_error_message(std::string* error_message);
  private:
  const std::string& _internal_error_message() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_error_message(const std::string& value);
  std::string* _internal_mutable_error_message();
  public:

  // int32 error = 1;
  void clear_error();
  int32_t error() const;
  void set_error(int32_t value);
  private:
  int32_t _internal_error() const;
  void _internal_set_error(int32_t value);
  public:

  // @@protoc_insertion_point(class_scope:message.AskAssistantResponse)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  struct Impl_ {
    ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr answer_;
    ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr error_message_;
    int32_t error_;
    mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_meeting_5fai_2eproto;
};
// ===================================================================


// ===================================================================

#ifdef __GNUC__
  #pragma GCC diagnostic push
  #pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// AskAssistantRequest

// string question = 1;
inline void AskAssistantRequest::clear_question() {
  _impl_.question_.ClearToEmpty();
}
inline const std::string& AskAssistantRequest::question() const {
  // @@protoc_insertion_point(field_get:message.AskAssistantRequest.question)
  return _internal_question();
}
template <typename ArgT0, typename... ArgT>
inline PROTOBUF_ALWAYS_INLINE
void AskAssistantRequest::set_question(ArgT0&& arg0, ArgT... args) {

 _impl_.question_.Set(static_cast<ArgT0 &&>(arg0), args..., GetArenaForAllocation());
  // @@protoc_insertion_point(field_set:message.AskAssistantRequest.question)
}
inline std::string* AskAssistantRequest::mutable_question() {
  std::string* _s = _internal_mutable_question();
  // @@protoc_insertion_point(field_mutable:message.AskAssistantRequest.question)
  return _s;
}
inline const std::string& AskAssistantRequest::_internal_question() const {
  return _impl_.question_.Get();
}
inline void AskAssistantRequest::_internal_set_question(const std::string& value) {

  _impl_.question_.Set(value, GetArenaForAllocation());
}
inline std::string* AskAssistantRequest::_internal_mutable_question() {

  return _impl_.question_.Mutable(GetArenaForAllocation());
}
inline std::string* AskAssistantRequest::release_question() {
  // @@protoc_insertion_point(field_release:message.AskAssistantRequest.question)
  return _impl_.question_.Release();
}
inline void AskAssistantRequest::set_allocated_question(std::string* question) {
  if (question != nullptr) {

  } else {

  }
  _impl_.question_.SetAllocated(question, GetArenaForAllocation());
#ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (_impl_.question_.IsDefault()) {
    _impl_.question_.Set("", GetArenaForAllocation());
  }
#endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  // @@protoc_insertion_point(field_set_allocated:message.AskAssistantRequest.question)
}

// -------------------------------------------------------------------

// AskAssistantResponse

// int32 error = 1;
inline void AskAssistantResponse::clear_error() {
  _impl_.error_ = 0;
}
inline int32_t AskAssistantResponse::_internal_error() const {
  return _impl_.error_;
}
inline int32_t AskAssistantResponse::error() const {
  // @@protoc_insertion_point(field_get:message.AskAssistantResponse.error)
  return _internal_error();
}
inline void AskAssistantResponse::_internal_set_error(int32_t value) {

  _impl_.error_ = value;
}
inline void AskAssistantResponse::set_error(int32_t value) {
  _internal_set_error(value);
  // @@protoc_insertion_point(field_set:message.AskAssistantResponse.error)
}

// string answer = 2;
inline void AskAssistantResponse::clear_answer() {
  _impl_.answer_.ClearToEmpty();
}
inline const std::string& AskAssistantResponse::answer() const {
  // @@protoc_insertion_point(field_get:message.AskAssistantResponse.answer)
  return _internal_answer();
}
template <typename ArgT0, typename... ArgT>
inline PROTOBUF_ALWAYS_INLINE
void AskAssistantResponse::set_answer(ArgT0&& arg0, ArgT... args) {

 _impl_.answer_.Set(static_cast<ArgT0 &&>(arg0), args..., GetArenaForAllocation());
  // @@protoc_insertion_point(field_set:message.AskAssistantResponse.answer)
}
inline std::string* AskAssistantResponse::mutable_answer() {
  std::string* _s = _internal_mutable_answer();
  // @@protoc_insertion_point(field_mutable:message.AskAssistantResponse.answer)
  return _s;
}
inline const std::string& AskAssistantResponse::_internal_answer() const {
  return _impl_.answer_.Get();
}
inline void AskAssistantResponse::_internal_set_answer(const std::string& value) {

  _impl_.answer_.Set(value, GetArenaForAllocation());
}
inline std::string* AskAssistantResponse::_internal_mutable_answer() {

  return _impl_.answer_.Mutable(GetArenaForAllocation());
}
inline std::string* AskAssistantResponse::release_answer() {
  // @@protoc_insertion_point(field_release:message.AskAssistantResponse.answer)
  return _impl_.answer_.Release();
}
inline void AskAssistantResponse::set_allocated_answer(std::string* answer) {
  if (answer != nullptr) {

  } else {

  }
  _impl_.answer_.SetAllocated(answer, GetArenaForAllocation());
#ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (_impl_.answer_.IsDefault()) {
    _impl_.answer_.Set("", GetArenaForAllocation());
  }
#endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  // @@protoc_insertion_point(field_set_allocated:message.AskAssistantResponse.answer)
}

// string error_message = 3;
inline void AskAssistantResponse::clear_error_message() {
  _impl_.error_message_.ClearToEmpty();
}
inline const std::string& AskAssistantResponse::error_message() const {
  // @@protoc_insertion_point(field_get:message.AskAssistantResponse.error_message)
  return _internal_error_message();
}
template <typename ArgT0, typename... ArgT>
inline PROTOBUF_ALWAYS_INLINE
void AskAssistantResponse::set_error_message(ArgT0&& arg0, ArgT... args) {

 _impl_.error_message_.Set(static_cast<ArgT0 &&>(arg0), args..., GetArenaForAllocation());
  // @@protoc_insertion_point(field_set:message.AskAssistantResponse.error_message)
}
inline std::string* AskAssistantResponse::mutable_error_message() {
  std::string* _s = _internal_mutable_error_message();
  // @@protoc_insertion_point(field_mutable:message.AskAssistantResponse.error_message)
  return _s;
}
inline const std::string& AskAssistantResponse::_internal_error_message() const {
  return _impl_.error_message_.Get();
}
inline void AskAssistantResponse::_internal_set_error_message(const std::string& value) {

  _impl_.error_message_.Set(value, GetArenaForAllocation());
}
inline std::string* AskAssistantResponse::_internal_mutable_error_message() {

  return _impl_.error_message_.Mutable(GetArenaForAllocation());
}
inline std::string* AskAssistantResponse::release_error_message() {
  // @@protoc_insertion_point(field_release:message.AskAssistantResponse.error_message)
  return _impl_.error_message_.Release();
}
inline void AskAssistantResponse::set_allocated_error_message(std::string* error_message) {
  if (error_message != nullptr) {

  } else {

  }
  _impl_.error_message_.SetAllocated(error_message, GetArenaForAllocation());
#ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (_impl_.error_message_.IsDefault()) {
    _impl_.error_message_.Set("", GetArenaForAllocation());
  }
#endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  // @@protoc_insertion_point(field_set_allocated:message.AskAssistantResponse.error_message)
}

#ifdef __GNUC__
  #pragma GCC diagnostic pop
#endif  // __GNUC__
// -------------------------------------------------------------------


// @@protoc_insertion_point(namespace_scope)

}  // namespace message

// @@protoc_insertion_point(global_scope)

#include <google/protobuf/port_undef.inc>
#endif  // GOOGLE_PROTOBUF_INCLUDED_GOOGLE_PROTOBUF_INCLUDED_meeting_5fai_2eproto
