// Generated by the gRPC C++ plugin.
// If you make any local change, they will be lost.
// source: meeting_ai.proto

#include "common/meeting_ai.pb.h"
#include "common/meeting_ai.grpc.pb.h"

#include <functional>
#include <grpcpp/support/async_stream.h>
#include <grpcpp/support/async_unary_call.h>
#include <grpcpp/impl/channel_interface.h>
#include <grpcpp/impl/client_unary_call.h>
#include <grpcpp/support/client_callback.h>
#include <grpcpp/support/message_allocator.h>
#include <grpcpp/support/method_handler.h>
#include <grpcpp/impl/rpc_service_method.h>
#include <grpcpp/support/server_callback.h>
#include <grpcpp/impl/codegen/server_callback_handlers.h>
#include <grpcpp/server_context.h>
#include <grpcpp/impl/service_type.h>
#include <grpcpp/support/sync_stream.h>
namespace message {

static const char* MeetingAiService_method_names[] = {
  "/message.MeetingAiService/AskAssistant",
};

std::unique_ptr< MeetingAiService::Stub> MeetingAiService::NewStub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options) {
  (void)options;
  std::unique_ptr< MeetingAiService::Stub> stub(new MeetingAiService::Stub(channel, options));
  return stub;
}

MeetingAiService::Stub::Stub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options)
  : channel_(channel), rpcmethod_AskAssistant_(MeetingAiService_method_names[0], options.suffix_for_stats(),::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  {}

::grpc::Status MeetingAiService::Stub::AskAssistant(::grpc::ClientContext* context, const ::message::AskAssistantRequest& request, ::message::AskAssistantResponse* response) {
  return ::grpc::internal::BlockingUnaryCall< ::message::AskAssistantRequest, ::message::AskAssistantResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), rpcmethod_AskAssistant_, context, request, response);
}

void MeetingAiService::Stub::async::AskAssistant(::grpc::ClientContext* context, const ::message::AskAssistantRequest* request, ::message::AskAssistantResponse* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall< ::message::AskAssistantRequest, ::message::AskAssistantResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_AskAssistant_, context, request, response, std::move(f));
}

void MeetingAiService::Stub::async::AskAssistant(::grpc::ClientContext* context, const ::message::AskAssistantRequest* request, ::message::AskAssistantResponse* response, ::grpc::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create< ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_AskAssistant_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::message::AskAssistantResponse>* MeetingAiService::Stub::PrepareAsyncAskAssistantRaw(::grpc::ClientContext* context, const ::message::AskAssistantRequest& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderHelper::Create< ::message::AskAssistantResponse, ::message::AskAssistantRequest, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), cq, rpcmethod_AskAssistant_, context, request);
}

::grpc::ClientAsyncResponseReader< ::message::AskAssistantResponse>* MeetingAiService::Stub::AsyncAskAssistantRaw(::grpc::ClientContext* context, const ::message::AskAssistantRequest& request, ::grpc::CompletionQueue* cq) {
  auto* result =
    this->PrepareAsyncAskAssistantRaw(context, request, cq);
  result->StartCall();
  return result;
}

MeetingAiService::Service::Service() {
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      MeetingAiService_method_names[0],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< MeetingAiService::Service, ::message::AskAssistantRequest, ::message::AskAssistantResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(
          [](MeetingAiService::Service* service,
             ::grpc::ServerContext* ctx,
             const ::message::AskAssistantRequest* req,
             ::message::AskAssistantResponse* resp) {
               return service->AskAssistant(ctx, req, resp);
             }, this)));
}

MeetingAiService::Service::~Service() {
}

::grpc::Status MeetingAiService::Service::AskAssistant(::grpc::ServerContext* context, const ::message::AskAssistantRequest* request, ::message::AskAssistantResponse* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}


}  // namespace message
