// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: meeting_ai.proto

#include "common/meeting_ai.pb.h"

#include <algorithm>

#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/extension_set.h>
#include <google/protobuf/wire_format_lite.h>
#include <google/protobuf/descriptor.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/reflection_ops.h>
#include <google/protobuf/wire_format.h>
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>

PROTOBUF_PRAGMA_INIT_SEG

namespace _pb = ::PROTOBUF_NAMESPACE_ID;
namespace _pbi = _pb::internal;

namespace message {
PROTOBUF_CONSTEXPR AskAssistantRequest::AskAssistantRequest(
    ::_pbi::ConstantInitialized): _impl_{
    /*decltype(_impl_.question_)*/{&::_pbi::fixed_address_empty_string, ::_pbi::ConstantInitialized{}}
  , /*decltype(_impl_._cached_size_)*/{}} {}
struct AskAssistantRequestDefaultTypeInternal {
  PROTOBUF_CONSTEXPR AskAssistantRequestDefaultTypeInternal()
      : _instance(::_pbi::ConstantInitialized{}) {}
  ~AskAssistantRequestDefaultTypeInternal() {}
  union {
    AskAssistantRequest _instance;
  };
};
PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 AskAssistantRequestDefaultTypeInternal _AskAssistantRequest_default_instance_;
PROTOBUF_CONSTEXPR AskAssistantResponse::AskAssistantResponse(
    ::_pbi::ConstantInitialized): _impl_{
    /*decltype(_impl_.answer_)*/{&::_pbi::fixed_address_empty_string, ::_pbi::ConstantInitialized{}}
  , /*decltype(_impl_.error_message_)*/{&::_pbi::fixed_address_empty_string, ::_pbi::ConstantInitialized{}}
  , /*decltype(_impl_.error_)*/0
  , /*decltype(_impl_._cached_size_)*/{}} {}
struct AskAssistantResponseDefaultTypeInternal {
  PROTOBUF_CONSTEXPR AskAssistantResponseDefaultTypeInternal()
      : _instance(::_pbi::ConstantInitialized{}) {}
  ~AskAssistantResponseDefaultTypeInternal() {}
  union {
    AskAssistantResponse _instance;
  };
};
PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 AskAssistantResponseDefaultTypeInternal _AskAssistantResponse_default_instance_;
}  // namespace message
static ::_pb::Metadata file_level_metadata_meeting_5fai_2eproto[2];
static constexpr ::_pb::EnumDescriptor const** file_level_enum_descriptors_meeting_5fai_2eproto = nullptr;
static constexpr ::_pb::ServiceDescriptor const** file_level_service_descriptors_meeting_5fai_2eproto = nullptr;

const uint32_t TableStruct_meeting_5fai_2eproto::offsets[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) = {
  ~0u,  // no _has_bits_
  PROTOBUF_FIELD_OFFSET(::message::AskAssistantRequest, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  ~0u,  // no _inlined_string_donated_
  PROTOBUF_FIELD_OFFSET(::message::AskAssistantRequest, _impl_.question_),
  ~0u,  // no _has_bits_
  PROTOBUF_FIELD_OFFSET(::message::AskAssistantResponse, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  ~0u,  // no _inlined_string_donated_
  PROTOBUF_FIELD_OFFSET(::message::AskAssistantResponse, _impl_.error_),
  PROTOBUF_FIELD_OFFSET(::message::AskAssistantResponse, _impl_.answer_),
  PROTOBUF_FIELD_OFFSET(::message::AskAssistantResponse, _impl_.error_message_),
};
static const ::_pbi::MigrationSchema schemas[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) = {
  { 0, -1, -1, sizeof(::message::AskAssistantRequest)},
  { 7, -1, -1, sizeof(::message::AskAssistantResponse)},
};

static const ::_pb::Message* const file_default_instances[] = {
  &::message::_AskAssistantRequest_default_instance_._instance,
  &::message::_AskAssistantResponse_default_instance_._instance,
};

const char descriptor_table_protodef_meeting_5fai_2eproto[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) =
  "\n\020meeting_ai.proto\022\007message\"\'\n\023AskAssist"
  "antRequest\022\020\n\010question\030\001 \001(\t\"L\n\024AskAssis"
  "tantResponse\022\r\n\005error\030\001 \001(\005\022\016\n\006answer\030\002 "
  "\001(\t\022\025\n\rerror_message\030\003 \001(\t2a\n\020MeetingAiS"
  "ervice\022M\n\014AskAssistant\022\034.message.AskAssi"
  "stantRequest\032\035.message.AskAssistantRespo"
  "nse\"\000b\006proto3"
  ;
static ::_pbi::once_flag descriptor_table_meeting_5fai_2eproto_once;
const ::_pbi::DescriptorTable descriptor_table_meeting_5fai_2eproto = {
    false, false, 253, descriptor_table_protodef_meeting_5fai_2eproto,
    "meeting_ai.proto",
    &descriptor_table_meeting_5fai_2eproto_once, nullptr, 0, 2,
    schemas, file_default_instances, TableStruct_meeting_5fai_2eproto::offsets,
    file_level_metadata_meeting_5fai_2eproto, file_level_enum_descriptors_meeting_5fai_2eproto,
    file_level_service_descriptors_meeting_5fai_2eproto,
};
PROTOBUF_ATTRIBUTE_WEAK const ::_pbi::DescriptorTable* descriptor_table_meeting_5fai_2eproto_getter() {
  return &descriptor_table_meeting_5fai_2eproto;
}

// Force running AddDescriptors() at dynamic initialization time.
PROTOBUF_ATTRIBUTE_INIT_PRIORITY2 static ::_pbi::AddDescriptorsRunner dynamic_init_dummy_meeting_5fai_2eproto(&descriptor_table_meeting_5fai_2eproto);
namespace message {

// ===================================================================

class AskAssistantRequest::_Internal {
 public:
};

AskAssistantRequest::AskAssistantRequest(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                         bool is_message_owned)
  : ::PROTOBUF_NAMESPACE_ID::Message(arena, is_message_owned) {
  SharedCtor(arena, is_message_owned);
  // @@protoc_insertion_point(arena_constructor:message.AskAssistantRequest)
}
AskAssistantRequest::AskAssistantRequest(const AskAssistantRequest& from)
  : ::PROTOBUF_NAMESPACE_ID::Message() {
  AskAssistantRequest* const _this = this; (void)_this;
  new (&_impl_) Impl_{
      decltype(_impl_.question_){}
    , /*decltype(_impl_._cached_size_)*/{}};

  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  _impl_.question_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
    _impl_.question_.Set("", GetArenaForAllocation());
  #endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (!from._internal_question().empty()) {
    _this->_impl_.question_.Set(from._internal_question(),
      _this->GetArenaForAllocation());
  }
  // @@protoc_insertion_point(copy_constructor:message.AskAssistantRequest)
}

inline void AskAssistantRequest::SharedCtor(
    ::_pb::Arena* arena, bool is_message_owned) {
  (void)arena;
  (void)is_message_owned;
  new (&_impl_) Impl_{
      decltype(_impl_.question_){}
    , /*decltype(_impl_._cached_size_)*/{}
  };
  _impl_.question_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
    _impl_.question_.Set("", GetArenaForAllocation());
  #endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
}

AskAssistantRequest::~AskAssistantRequest() {
  // @@protoc_insertion_point(destructor:message.AskAssistantRequest)
  if (auto *arena = _internal_metadata_.DeleteReturnArena<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>()) {
  (void)arena;
    return;
  }
  SharedDtor();
}

inline void AskAssistantRequest::SharedDtor() {
  GOOGLE_DCHECK(GetArenaForAllocation() == nullptr);
  _impl_.question_.Destroy();
}

void AskAssistantRequest::SetCachedSize(int size) const {
  _impl_._cached_size_.Set(size);
}

void AskAssistantRequest::Clear() {
// @@protoc_insertion_point(message_clear_start:message.AskAssistantRequest)
  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  _impl_.question_.ClearToEmpty();
  _internal_metadata_.Clear<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

const char* AskAssistantRequest::_InternalParse(const char* ptr, ::_pbi::ParseContext* ctx) {
#define CHK_(x) if (PROTOBUF_PREDICT_FALSE(!(x))) goto failure
  while (!ctx->Done(&ptr)) {
    uint32_t tag;
    ptr = ::_pbi::ReadTag(ptr, &tag);
    switch (tag >> 3) {
      // string question = 1;
      case 1:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 10)) {
          auto str = _internal_mutable_question();
          ptr = ::_pbi::InlineGreedyStringParser(str, ptr, ctx);
          CHK_(ptr);
          CHK_(::_pbi::VerifyUTF8(str, "message.AskAssistantRequest.question"));
        } else
          goto handle_unusual;
        continue;
      default:
        goto handle_unusual;
    }  // switch
  handle_unusual:
    if ((tag == 0) || ((tag & 7) == 4)) {
      CHK_(ptr);
      ctx->SetLastTag(tag);
      goto message_done;
    }
    ptr = UnknownFieldParse(
        tag,
        _internal_metadata_.mutable_unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(),
        ptr, ctx);
    CHK_(ptr != nullptr);
  }  // while
message_done:
  return ptr;
failure:
  ptr = nullptr;
  goto message_done;
#undef CHK_
}

uint8_t* AskAssistantRequest::_InternalSerialize(
    uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:message.AskAssistantRequest)
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  // string question = 1;
  if (!this->_internal_question().empty()) {
    ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::VerifyUtf8String(
      this->_internal_question().data(), static_cast<int>(this->_internal_question().length()),
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::SERIALIZE,
      "message.AskAssistantRequest.question");
    target = stream->WriteStringMaybeAliased(
        1, this->_internal_question(), target);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target = ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
        _internal_metadata_.unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(::PROTOBUF_NAMESPACE_ID::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:message.AskAssistantRequest)
  return target;
}

size_t AskAssistantRequest::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:message.AskAssistantRequest)
  size_t total_size = 0;

  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // string question = 1;
  if (!this->_internal_question().empty()) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::StringSize(
        this->_internal_question());
  }

  return MaybeComputeUnknownFieldsSize(total_size, &_impl_._cached_size_);
}

const ::PROTOBUF_NAMESPACE_ID::Message::ClassData AskAssistantRequest::_class_data_ = {
    ::PROTOBUF_NAMESPACE_ID::Message::CopyWithSourceCheck,
    AskAssistantRequest::MergeImpl
};
const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*AskAssistantRequest::GetClassData() const { return &_class_data_; }


void AskAssistantRequest::MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg) {
  auto* const _this = static_cast<AskAssistantRequest*>(&to_msg);
  auto& from = static_cast<const AskAssistantRequest&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:message.AskAssistantRequest)
  GOOGLE_DCHECK_NE(&from, _this);
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  if (!from._internal_question().empty()) {
    _this->_internal_set_question(from._internal_question());
  }
  _this->_internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
}

void AskAssistantRequest::CopyFrom(const AskAssistantRequest& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:message.AskAssistantRequest)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool AskAssistantRequest::IsInitialized() const {
  return true;
}

void AskAssistantRequest::InternalSwap(AskAssistantRequest* other) {
  using std::swap;
  auto* lhs_arena = GetArenaForAllocation();
  auto* rhs_arena = other->GetArenaForAllocation();
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::InternalSwap(
      &_impl_.question_, lhs_arena,
      &other->_impl_.question_, rhs_arena
  );
}

::PROTOBUF_NAMESPACE_ID::Metadata AskAssistantRequest::GetMetadata() const {
  return ::_pbi::AssignDescriptors(
      &descriptor_table_meeting_5fai_2eproto_getter, &descriptor_table_meeting_5fai_2eproto_once,
      file_level_metadata_meeting_5fai_2eproto[0]);
}

// ===================================================================

class AskAssistantResponse::_Internal {
 public:
};

AskAssistantResponse::AskAssistantResponse(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                         bool is_message_owned)
  : ::PROTOBUF_NAMESPACE_ID::Message(arena, is_message_owned) {
  SharedCtor(arena, is_message_owned);
  // @@protoc_insertion_point(arena_constructor:message.AskAssistantResponse)
}
AskAssistantResponse::AskAssistantResponse(const AskAssistantResponse& from)
  : ::PROTOBUF_NAMESPACE_ID::Message() {
  AskAssistantResponse* const _this = this; (void)_this;
  new (&_impl_) Impl_{
      decltype(_impl_.answer_){}
    , decltype(_impl_.error_message_){}
    , decltype(_impl_.error_){}
    , /*decltype(_impl_._cached_size_)*/{}};

  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  _impl_.answer_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
    _impl_.answer_.Set("", GetArenaForAllocation());
  #endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (!from._internal_answer().empty()) {
    _this->_impl_.answer_.Set(from._internal_answer(),
      _this->GetArenaForAllocation());
  }
  _impl_.error_message_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
    _impl_.error_message_.Set("", GetArenaForAllocation());
  #endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (!from._internal_error_message().empty()) {
    _this->_impl_.error_message_.Set(from._internal_error_message(),
      _this->GetArenaForAllocation());
  }
  _this->_impl_.error_ = from._impl_.error_;
  // @@protoc_insertion_point(copy_constructor:message.AskAssistantResponse)
}

inline void AskAssistantResponse::SharedCtor(
    ::_pb::Arena* arena, bool is_message_owned) {
  (void)arena;
  (void)is_message_owned;
  new (&_impl_) Impl_{
      decltype(_impl_.answer_){}
    , decltype(_impl_.error_message_){}
    , decltype(_impl_.error_){0}
    , /*decltype(_impl_._cached_size_)*/{}
  };
  _impl_.answer_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
    _impl_.answer_.Set("", GetArenaForAllocation());
  #endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  _impl_.error_message_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
    _impl_.error_message_.Set("", GetArenaForAllocation());
  #endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
}

AskAssistantResponse::~AskAssistantResponse() {
  // @@protoc_insertion_point(destructor:message.AskAssistantResponse)
  if (auto *arena = _internal_metadata_.DeleteReturnArena<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>()) {
  (void)arena;
    return;
  }
  SharedDtor();
}

inline void AskAssistantResponse::SharedDtor() {
  GOOGLE_DCHECK(GetArenaForAllocation() == nullptr);
  _impl_.answer_.Destroy();
  _impl_.error_message_.Destroy();
}

void AskAssistantResponse::SetCachedSize(int size) const {
  _impl_._cached_size_.Set(size);
}

void AskAssistantResponse::Clear() {
// @@protoc_insertion_point(message_clear_start:message.AskAssistantResponse)
  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  _impl_.answer_.ClearToEmpty();
  _impl_.error_message_.ClearToEmpty();
  _impl_.error_ = 0;
  _internal_metadata_.Clear<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

const char* AskAssistantResponse::_InternalParse(const char* ptr, ::_pbi::ParseContext* ctx) {
#define CHK_(x) if (PROTOBUF_PREDICT_FALSE(!(x))) goto failure
  while (!ctx->Done(&ptr)) {
    uint32_t tag;
    ptr = ::_pbi::ReadTag(ptr, &tag);
    switch (tag >> 3) {
      // int32 error = 1;
      case 1:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 8)) {
          _impl_.error_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint32(&ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      // string answer = 2;
      case 2:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 18)) {
          auto str = _internal_mutable_answer();
          ptr = ::_pbi::InlineGreedyStringParser(str, ptr, ctx);
          CHK_(ptr);
          CHK_(::_pbi::VerifyUTF8(str, "message.AskAssistantResponse.answer"));
        } else
          goto handle_unusual;
        continue;
      // string error_message = 3;
      case 3:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 26)) {
          auto str = _internal_mutable_error_message();
          ptr = ::_pbi::InlineGreedyStringParser(str, ptr, ctx);
          CHK_(ptr);
          CHK_(::_pbi::VerifyUTF8(str, "message.AskAssistantResponse.error_message"));
        } else
          goto handle_unusual;
        continue;
      default:
        goto handle_unusual;
    }  // switch
  handle_unusual:
    if ((tag == 0) || ((tag & 7) == 4)) {
      CHK_(ptr);
      ctx->SetLastTag(tag);
      goto message_done;
    }
    ptr = UnknownFieldParse(
        tag,
        _internal_metadata_.mutable_unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(),
        ptr, ctx);
    CHK_(ptr != nullptr);
  }  // while
message_done:
  return ptr;
failure:
  ptr = nullptr;
  goto message_done;
#undef CHK_
}

uint8_t* AskAssistantResponse::_InternalSerialize(
    uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:message.AskAssistantResponse)
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  // int32 error = 1;
  if (this->_internal_error() != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteInt32ToArray(1, this->_internal_error(), target);
  }

  // string answer = 2;
  if (!this->_internal_answer().empty()) {
    ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::VerifyUtf8String(
      this->_internal_answer().data(), static_cast<int>(this->_internal_answer().length()),
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::SERIALIZE,
      "message.AskAssistantResponse.answer");
    target = stream->WriteStringMaybeAliased(
        2, this->_internal_answer(), target);
  }

  // string error_message = 3;
  if (!this->_internal_error_message().empty()) {
    ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::VerifyUtf8String(
      this->_internal_error_message().data(), static_cast<int>(this->_internal_error_message().length()),
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::SERIALIZE,
      "message.AskAssistantResponse.error_message");
    target = stream->WriteStringMaybeAliased(
        3, this->_internal_error_message(), target);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target = ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
        _internal_metadata_.unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(::PROTOBUF_NAMESPACE_ID::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:message.AskAssistantResponse)
  return target;
}

size_t AskAssistantResponse::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:message.AskAssistantResponse)
  size_t total_size = 0;

  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // string answer = 2;
  if (!this->_internal_answer().empty()) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::StringSize(
        this->_internal_answer());
  }

  // string error_message = 3;
  if (!this->_internal_error_message().empty()) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::StringSize(
        this->_internal_error_message());
  }

  // int32 error = 1;
  if (this->_internal_error() != 0) {
    total_size += ::_pbi::WireFormatLite::Int32SizePlusOne(this->_internal_error());
  }

  return MaybeComputeUnknownFieldsSize(total_size, &_impl_._cached_size_);
}

const ::PROTOBUF_NAMESPACE_ID::Message::ClassData AskAssistantResponse::_class_data_ = {
    ::PROTOBUF_NAMESPACE_ID::Message::CopyWithSourceCheck,
    AskAssistantResponse::MergeImpl
};
const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*AskAssistantResponse::GetClassData() const { return &_class_data_; }


void AskAssistantResponse::MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg) {
  auto* const _this = static_cast<AskAssistantResponse*>(&to_msg);
  auto& from = static_cast<const AskAssistantResponse&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:message.AskAssistantResponse)
  GOOGLE_DCHECK_NE(&from, _this);
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  if (!from._internal_answer().empty()) {
    _this->_internal_set_answer(from._internal_answer());
  }
  if (!from._internal_error_message().empty()) {
    _this->_internal_set_error_message(from._internal_error_message());
  }
  if (from._internal_error() != 0) {
    _this->_internal_set_error(from._internal_error());
  }
  _this->_internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
}

void AskAssistantResponse::CopyFrom(const AskAssistantResponse& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:message.AskAssistantResponse)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool AskAssistantResponse::IsInitialized() const {
  return true;
}

void AskAssistantResponse::InternalSwap(AskAssistantResponse* other) {
  using std::swap;
  auto* lhs_arena = GetArenaForAllocation();
  auto* rhs_arena = other->GetArenaForAllocation();
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::InternalSwap(
      &_impl_.answer_, lhs_arena,
      &other->_impl_.answer_, rhs_arena
  );
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::InternalSwap(
      &_impl_.error_message_, lhs_arena,
      &other->_impl_.error_message_, rhs_arena
  );
  swap(_impl_.error_, other->_impl_.error_);
}

::PROTOBUF_NAMESPACE_ID::Metadata AskAssistantResponse::GetMetadata() const {
  return ::_pbi::AssignDescriptors(
      &descriptor_table_meeting_5fai_2eproto_getter, &descriptor_table_meeting_5fai_2eproto_once,
      file_level_metadata_meeting_5fai_2eproto[1]);
}

// @@protoc_insertion_point(namespace_scope)
}  // namespace message
PROTOBUF_NAMESPACE_OPEN
template<> PROTOBUF_NOINLINE ::message::AskAssistantRequest*
Arena::CreateMaybeMessage< ::message::AskAssistantRequest >(Arena* arena) {
  return Arena::CreateMessageInternal< ::message::AskAssistantRequest >(arena);
}
template<> PROTOBUF_NOINLINE ::message::AskAssistantResponse*
Arena::CreateMaybeMessage< ::message::AskAssistantResponse >(Arena* arena) {
  return Arena::CreateMessageInternal< ::message::AskAssistantResponse >(arena);
}
PROTOBUF_NAMESPACE_CLOSE

// @@protoc_insertion_point(global_scope)
#include <google/protobuf/port_undef.inc>
